version: '3'
services:
  www:
    image: php:8.1.1-apache
    volumes:
      - "./php/:/var/www/html"
    ports:
      - 5000:80
      - 5443:443
    networks:
      - lamp-docker
    command: >
      sh -c "docker-php-ext-install pdo pdo_mysql mysqli && apache2-foreground"
    restart: unless-stopped
  networks:
  lamp-docker:
    driver: bridge
